### ISSUE TITLE
Adding user silently fails

### ISSUE THREAD

**Issue by arvigeus** [qdm12/meemo#7]
```sh
$ sudo ./commands.sh add arvigeus arvigeus
====== Adding user ======
Adding user arvigeus with password arvigeus
Using local auth file:  /users.json
Done.
```

```sh
sudo ./commands.sh ls                   
====== List of users ======
Using local auth file:  /users.json
No users. Use `admin user-add` to add some.
```

I am setting permissions beforehand:

```sh
# Setup meemo
sudo mkdir -p ./data/meemo
sudo touch ./data/meemo/users.json
 # set ownership to map container user ID 1000
sudo chown 1000 ./data/meemo/users.json ./data/meemo/data ./data/meemo/db
#  # set permissions
sudo chmod 400 ./data/meemo/users.json
sudo chmod 700 ./data/meemo/data ./data/meemo/db
```

If it matters, my config:

```yml
  meemo:
    image: qmcgaw/meemo
    container_name: meemo
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./data/meemo/users.json:/users.json
      - ./data/meemo/data:/data
    environment:
      - PORT=3000
      - CLOUDRON_MONGODB_URL=mongodb://meemodb:27017/meemo
      - CLOUDRON_APP_ORIGIN=http://notes.${DOMAIN}
      - LOCAL_AUTH_FILE=/users.json
    # ports:
    #   - 3000:3000/tcp
    depends_on:
      - meemodb
    labels:
      - traefik.http.routers.meemo.entrypoints=https
      - traefik.http.routers.meemo.rule=Host(`notes.${DOMAIN}`)
      - traefik.http.routers.meemo.tls=true
      - traefik.http.routers.meemo.tls.certresolver=${CERT_RESOLVER}
      ## HTTP Services
      - "traefik.http.routers.meemo.service=meemo-svc"
      - "traefik.http.services.meemo-svc.loadbalancer.server.port=3000"
```

I also tried not using `- ./data/meemo/users.json:/users.json` volume binding to eliminate the possibility of permission issue.

On a related note: This method does not work with complex passwords.
